### ISSUE TITLE
Issue with LUAD arm-level CNA data

### ISSUE THREAD

**Issue by marcus-r-kelly** [cBioPortal/datahub#1818] opened 2023-04-26 18:24 UTC
The arm-level CNA data file for the TCGA pan-cancer atlas LUAD cohort (https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/luad_tcga_pan_can_atlas_2018/data_armlevel_cna.txt) has no "Gain" values, and several scattered "NA" values that I believe correspond to arm-level gains. This issue is not present in other cohorts I've examined, but I'm not sure how widespread it is.

**Comment by sbabyanusha** [comment] 2023-04-26 22:40
@marcus-r-kelly Thanks for bringing this to our attention. We are working on fixing it and the data will be fixed by tomorrow EOD.

**Comment by sbabyanusha** [comment] 2023-04-27 14:22
The issue is fixed. @marcus-r-kelly

**Closed** 2023-04-27 14:21 UTC
