### ISSUE TITLE
Chen et al. Genomic landscape of lung adenocarcinoma in East Asians. Nature Genetics 2020.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1108] opened 2020-04-30 19:50 UTC
https://www.nature.com/articles/s41588-019-0569-6

Data: https://mskcc.box.com/s/qd1wkaympzxxz0q8vx97t9e0shszx582

https://src.gisapps.org/OncoSG_public/study/summary?id=GIS031

In the description, please mention "courtesy of [OncoSG](https://src.gisapps.org/OncoSG/)"

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by cbrueffer** [comment] 2020-06-23 10:09
This is a duplicate of https://github.com/cBioPortal/datahub/issues/1027

**Closed** 2020-06-29 19:17 UTC
Labels: new public study
